services:
  nlw-agents-pg:
    container_name: pgvector
    image: pgvector/pgvector:0.8.0-pg17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    ports:
      - "8080:5432"
    volumes:
      - ./pg_data.sql:/docker-entrypoint-initdb.d/pg_data.sql
