services:
  pg-vector:
    container_name: pgvector
    image: pgvector/pgvector:0.8.0-pg17
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data.sql:/docker-entrypoint-initdb.d/pg_data.sql
